### ISSUE TITLE
1.2.10 breaks a PT-internal project

### ISSUE THREAD

**Issue by jmartin-pt** [palantir/gradle-configuration-resolver-plugin#32]
A PT-internal project (see foundry/operational-transform PR number 17) breaks  when running `gw check` after upgrading the gradle config resolve plugin from 1.2.9 to 1.2.10. It doesn't seem to work on any version at least up to 1.2.15.

**Comment by jmcampanini** [comment]
this plugin has only released up to 0.3.0 (see [releases](https://github.com/palantir/gradle-configuration-resolver-plugin/releases))

**Comment by jmartin-pt** [comment]
Dammit, wrong plugin. Sorry. (I'd initially thought configuration resolver was the problem, and started filing the bug here, then realized it was gradle-processors, and filed the bug here anyway. 🤦‍♂️ )
